/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ocr;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import net.sourceforge.tess4j.ITesseract;
import net.sourceforge.tess4j.Tesseract;
import net.sourceforge.tess4j.TesseractException;
import net.sourceforge.tess4j.util.ImageHelper;
import net.sourceforge.tess4j.util.LoadLibs;

/**
 *
 * @author user
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        txt.setText("hello");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            //圖片位置
            String ch = "C:\\eclipse-workspace\\tessdata\\0001.jpg";
            //將辨識後的文字輸出為textbox內容
            //readChar 的三個變數範例
            //圖片路徑要完整指到圖片為止 C:\\eclipse-workspace\\tessdata\\0001.jpg
            //訓練庫路徑 
                //XXX.traineddata 訓練檔案的所在資料夾 
                //XXX.traineddata 訓練檔在 C:\\eclipse-workspace\\tessdata\\XXX.traineddata 的話
                //該變數就是C:\\eclipse-workspace\\tessdata
            //語言字型檔
                //XXX.traineddata 的檔名，比如這裡是辨識英數字，使用網上現成的eng.traineddata
                //這裡就傳入eng
                //或者使用自行透過jTessBoxEditor軟體訓練產生的其他名稱的例如abc.traineddata
                //這裡就要改傳入abc
            txt.setText(readChar(ch, "C:\\eclipse-workspace\\tessdata", "eng"));
            
            //測試行，將結果輸出在主控台
            //System.out.println(readChar(ch, "C:\\eclipse-workspace\\tessdata", "eng"));            
        } catch (IOException e) {
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    //////////////////////////////////////////////////////
    //指定一個位置與名稱用於暫存被放大與銳化、黑白處裡的圖片
    private static File testfile = new File("C:\\eclipse-workspace\\tessdata\\img_temp.jpg");

    /**
     * 從圖片中提取文字
     *
     * @param path 圖片路徑
     * @param dataPath 訓練庫路徑
     * @param language 語言字型檔
     * @return
     */
    public static String readChar(String path, String dataPath, String language) throws IOException {
        ITesseract instance = new Tesseract();
        instance.setDatapath(dataPath);
        //英文庫識別數字比較準確
        instance.setLanguage(language);
        // double start = System.currentTimeMillis();
        BufferedImage textImage = ImageIO.read(new File(path));
        // 這裏對圖片黑白處理,增強識別率.這裏先通過截圖,截取圖片中需要識別的部分
        textImage = ImageHelper.convertImageToGrayscale(textImage);
        // 圖片銳化
        textImage = ImageHelper.convertImageToBinary(textImage);
        // 圖片放大倍數,增強識別率(很多圖片本身無法識別,放大5倍時就可以輕易識,但是考濾到客戶電腦配置低,針式打印機打印不連貫的問題,這裏就放大5倍)
        textImage = ImageHelper.getScaledInstance(textImage, textImage.getWidth() * 5, textImage.getHeight() * 5);

        textImage = ImageHelper.convertImageToBinary(textImage);
        ImageIO.write(textImage, "jpg", testfile);

        return getOCRText(instance, testfile);

        //////////////////////////////////////////////////////
    }

    /**
     * 識別圖片檔案中的文字
     *
     * @param instance
     * @param imageFile
     * @return
     */
    private static String getOCRText(ITesseract instance, File imageFile) {
        String result = null;
        try {
            result = instance.doOCR(imageFile);
            testfile.delete();
        } catch (TesseractException e) {
            e.printStackTrace();
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
